pipeline {
    agent any  // Runs on any available Jenkins agent

    environment {
        JAVA_HOME = 'C:\\Program Files\\Java\\jdk-21'  // Set Java path
        PATH = "$JAVA_HOME/bin:$PATH"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/Selvaganapathi-414/Mobicomm.git'  // Replace with your repo URL
            }
        }

        stage('Build') {
            steps {
				dir('Backend') { 
					sh 'mvn clean package'
				}
            }
        }

        stage('Run Application') {
            steps {
				dir('Backend') {
                script {
                    sh 'nohup java -jar target/*.jar > app.log 2>&1 &'
                }
                }
            }
        }

        stage('Show Logs') {
            steps {
				dir('Backend') {
                script {
                    sh 'tail -f app.log'
                }
                }
            }
        }
    }

    post {
        success {
            echo "✅ Build and deployment successful!"
        }
        failure {
            echo "❌ Build failed! Check logs for errors."
        }
    }
}
